/** Country -> flag emoji for the World Cup field (names as the TxLINE feed spells them). */
const FLAGS: Record<string, string> = {
  USA: "🇺🇸",
  "Bosnia & Herzegovina": "🇧🇦",
  Argentina: "🇦🇷",
  "Cape Verde": "🇨🇻",
  Australia: "🇦🇺",
  Egypt: "🇪🇬",
  Colombia: "🇨🇴",
  Ghana: "🇬🇭",
  Spain: "🇪🇸",
  Austria: "🇦🇹",
  Switzerland: "🇨🇭",
  Algeria: "🇩🇿",
  Portugal: "🇵🇹",
  Croatia: "🇭🇷",
  Canada: "🇨🇦",
  Morocco: "🇲🇦",
  Brazil: "🇧🇷",
  Norway: "🇳🇴",
  Paraguay: "🇵🇾",
  France: "🇫🇷",
  Mexico: "🇲🇽",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Belgium: "🇧🇪",
  Netherlands: "🇳🇱",
  Germany: "🇩🇪",
  Japan: "🇯🇵",
  "South Korea": "🇰🇷",
  Senegal: "🇸🇳",
  Uruguay: "🇺🇾",
  Ecuador: "🇪🇨",
  Iran: "🇮🇷",
  "Saudi Arabia": "🇸🇦",
  Poland: "🇵🇱",
  Denmark: "🇩🇰",
  Serbia: "🇷🇸",
  Tunisia: "🇹🇳",
  Nigeria: "🇳🇬",
  Cameroon: "🇨🇲",
  Qatar: "🇶🇦",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Italy: "🇮🇹",
};

export function flagFor(team: string): string {
  return FLAGS[team] ?? "⚽";
}
